"""database initialization

Revision ID: bb1b84b15cf6
Revises: 
Create Date: 2026-08-25 10:29:35.297305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1b84b15cf6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_name',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pokedex_id', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('owned', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(length=500), nullable=False),
    sa.Column('set_product', sa.String(length=500), nullable=False),
    sa.Column('card_number', sa.String(length=10), nullable=True),
    sa.Column('variant_printing', sa.String(length=500), nullable=False),
    sa.Column('representative_language', sa.String(length=500), nullable=False),
    sa.Column('all_language', sa.String(length=500), nullable=False),
    sa.Column('languages_count', sa.Integer(), nullable=False),
    sa.Column('same_card_other_language', sa.Boolean(), nullable=False),
    sa.Column('other_languages', sa.String(length=500), nullable=True),
    sa.Column('release_status', sa.String(length=25), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.Column('legacy_id', sa.String(length=25), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('card_image', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon_name.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_details_owned'), 'pokemon_details', ['owned'], unique=False)
    op.create_index(op.f('ix_pokemon_details_pokemon_id'), 'pokemon_details', ['pokemon_id'], unique=False)
    op.create_index(op.f('ix_pokemon_details_release_date'), 'pokemon_details', ['release_date'], unique=False)
    op.create_index(op.f('ix_pokemon_details_release_status'), 'pokemon_details', ['release_status'], unique=False)
    op.create_index(op.f('ix_pokemon_details_set_product'), 'pokemon_details', ['set_product'], unique=False)
    op.create_index(op.f('ix_pokemon_details_variant_printing'), 'pokemon_details', ['variant_printing'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_details_variant_printing'), table_name='pokemon_details')
    op.drop_index(op.f('ix_pokemon_details_set_product'), table_name='pokemon_details')
    op.drop_index(op.f('ix_pokemon_details_release_status'), table_name='pokemon_details')
    op.drop_index(op.f('ix_pokemon_details_release_date'), table_name='pokemon_details')
    op.drop_index(op.f('ix_pokemon_details_pokemon_id'), table_name='pokemon_details')
    op.drop_index(op.f('ix_pokemon_details_owned'), table_name='pokemon_details')
    op.drop_table('pokemon_details')
    op.drop_table('user')
    op.drop_table('pokemon_name')
    # ### end Alembic commands ###
